version: 2
jobs:
  build:
    working_directory: ~/example
    docker:
      - image: circleci/node:12-browsers
    steps:
      # Checkout the code from the branch into the working_directory
      - checkout
      # Log the current branch
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      # Restore local dependencies from cache
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
          - v1-dependencies-
      # Install project dependencies
      - run:
          name: Install local dependencies
          command: npm install
      # Cache local dependencies if they don't exist
      - save_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          paths:
              - node_modules
      # Lint the source code
      #- run:
      #    name: Linting
      #    command: npm run lint
      # Test the source code
      - run:
          name: Testing
          command: npm run test -- --no-watch --no-progress --browsers=ChromeHeadless
      # End to End test
      - run:
          name: End to End Test
          command: npm run e2e
  tag:
    machine: true
    steps:
      - checkout
      # build and push Docker image
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -f Dockerfile-prod -t example:$TAG .     
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker tag example:$TAG docker.pkg.github.com/keyau/example/example:$TAG
          docker push docker.pkg.github.com/keyau/example/example:$TAG
workflows:
  version: 2
  my_workflow:
    jobs:
      - build
      - tag:
          requires:
            - build
          filters:  # using regex filters requires the entire branch to match
            branches:
              only:  # only branches matching the below regex filters will run
                - master